#!/usr/bin/env node
/**
 * Generates the curriculum coverage matrix:
 * lessons × PA statute subjects × band, plus per-band subject totals.
 *
 *   npm run coverage
 *
 * Writes content/coverage.md (committed snapshot — regenerate after edits).
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { loadBands, loadPaAlignment } from './lib/load-content.mjs';

const REPO_ROOT = join(dirname(new URL(import.meta.url).pathname), '..');

const bands = await loadBands();
const pa = await loadPaAlignment();

const SUBJECT_ORDER = ['english', 'math', 'art', 'science', 'social', 'health', 'music', 'safety'];
const lines = [];
lines.push('# Meadow Curriculum Coverage');
lines.push('');
lines.push(`> Generated by \`npm run coverage\`. ${new Date().toISOString().slice(0, 10)}`);
lines.push('');

// --- per-band lesson tables ---
for (const band of bands) {
  const pathSorted = [...band.lessons].sort((a, b) => (a.pathOrder ?? 99) - (b.pathOrder ?? 99));
  lines.push(`## ${band.label} (${band.id}) — ${band.lessons.length} lessons`);
  lines.push('');
  lines.push('| # | Lesson | Subject | Min | PA subjects | Standards |');
  lines.push('|---|--------|---------|-----|-------------|-----------|');
  for (const l of pathSorted) {
    const paSubjects = (l.pa?.statuteSubjects ?? []).join('; ');
    const tags = (l.pa?.standardsTags ?? []).join('; ');
    lines.push(`| ${l.pathOrder ?? '—'} | ${l.title} (\`${l.id}\`) | ${l.subject} | ${l.minutes} | ${paSubjects} | ${tags} |`);
  }
  lines.push('');
}

// --- subject totals per band ---
lines.push('## Subject totals per band');
lines.push('');
lines.push(`| Subject | ${bands.map((b) => b.id).join(' | ')} | Total |`);
lines.push(`|---------|${bands.map(() => '---').join('|')}|-------|`);
for (const subject of SUBJECT_ORDER) {
  const counts = bands.map((b) => b.lessons.filter((l) => l.subject === subject).length);
  lines.push(`| ${subject} | ${counts.join(' | ')} | ${counts.reduce((a, b) => a + b, 0)} |`);
}
lines.push('');

// --- PA statute subject coverage ---
lines.push('## PA statute subject coverage');
lines.push('');
lines.push(`| PA subject | ${bands.map((b) => b.id).join(' | ')} |`);
lines.push(`|------------|${bands.map(() => '---').join('|')}|`);
for (const subject of pa.PA_ELEMENTARY_SUBJECTS) {
  const cells = bands.map((b) =>
    b.lessons.some((l) => l.pa?.statuteSubjects?.includes(subject)) ? '✅' : '⬜',
  );
  lines.push(`| ${subject} | ${cells.join(' | ')} |`);
}
lines.push('');

const outPath = join(REPO_ROOT, 'content', 'coverage.md');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'));

const total = bands.reduce((n, b) => n + b.lessons.length, 0);
console.log(`Wrote ${outPath} (${bands.length} bands, ${total} lessons).`);
